#!/usr/bin/env python3
"""
Guardian — WAV to C Array Converter

Converts a 16 kHz mono 16-bit WAV file to a C int16_t array header that can
be #included directly in firmware source.

Usage:
    python3 wav_to_c_array.py <input.wav> <var_name> <output.h>

Example:
    python3 wav_to_c_array.py results/audio_test_set/speech_001.wav \\
        speech_sample firmware/src/testdata/speech_sample.h

    python3 wav_to_c_array.py results/audio_test_set/noise_001.wav \\
        noise_sample firmware/src/testdata/noise_sample.h
"""
import sys
import os
import wave
import struct


def main():
    if len(sys.argv) != 4:
        print(__doc__)
        sys.exit(1)

    wav_path = sys.argv[1]
    var_name = sys.argv[2]
    out_path = sys.argv[3]

    # ── Load WAV ──────────────────────────────────────────────────────────────
    with wave.open(wav_path, 'r') as wf:
        channels   = wf.getnchannels()
        sampwidth  = wf.getsampwidth()
        framerate  = wf.getframerate()
        n_frames   = wf.getnframes()
        raw        = wf.readframes(n_frames)

    if channels != 1:
        print(f"ERROR: {wav_path} has {channels} channels — need mono.")
        sys.exit(1)
    if sampwidth != 2:
        print(f"ERROR: {wav_path} is {sampwidth*8}-bit — need 16-bit.")
        sys.exit(1)

    samples  = struct.unpack(f'<{n_frames}h', raw)
    duration = n_frames / framerate

    # ── Write header ──────────────────────────────────────────────────────────
    guard     = var_name.upper() + '_H'
    var_upper = var_name.upper()

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, 'w') as f:
        f.write(f'#ifndef {guard}\n')
        f.write(f'#define {guard}\n')
        f.write(f'/* Auto-generated by wav_to_c_array.py — DO NOT EDIT */\n')
        f.write(f'/* Source  : {os.path.basename(wav_path)} */\n')
        f.write(f'/* Format  : {framerate} Hz, mono, 16-bit PCM */\n')
        f.write(f'/* Samples : {n_frames} ({duration:.2f} s) */\n')
        f.write(f'/* Flash   : ~{n_frames * 2 // 1024} KB */\n')
        f.write(f'\n')
        f.write(f'#define {var_upper}_SAMPLE_COUNT {n_frames}U\n')
        f.write(f'#define {var_upper}_SAMPLE_RATE  {framerate}U\n')
        f.write(f'\n')
        f.write(f'static const int16_t {var_name}[{n_frames}] = {{\n')

        # 16 samples per line for readability + compact output
        COLS = 16
        for i in range(0, n_frames, COLS):
            chunk = samples[i:i + COLS]
            line  = '    ' + ', '.join(f'{s:6d}' for s in chunk) + ','
            f.write(line + '\n')

        f.write('};\n')
        f.write(f'\n#endif /* {guard} */\n')

    print(f"  Input  : {wav_path}")
    print(f"  Var    : {var_name}[{n_frames}]  ({duration:.2f}s @ {framerate} Hz)")
    print(f"  Flash  : ~{n_frames * 2 // 1024} KB")
    print(f"  Output : {out_path}")


if __name__ == '__main__':
    main()
